import { chromium } from 'playwright';
import http from 'http'; import fs from 'fs'; import path from 'path';
const ROOT=path.resolve('dist');
const MIME={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.webp':'image/webp','.jpg':'image/jpeg','.png':'image/png','.svg':'image/svg+xml','.ico':'image/x-icon','.webmanifest':'application/manifest+json'};
const srv=http.createServer((q,r)=>{let p=decodeURIComponent(q.url.split('?')[0]);let f=path.join(ROOT,p);
 if(!fs.existsSync(f)||fs.statSync(f).isDirectory())f=path.join(ROOT,'index.html');
 r.writeHead(200,{'Content-Type':MIME[path.extname(f)]||'application/octet-stream'});fs.createReadStream(f).pipe(r);});
await new Promise(r=>srv.listen(4194,r));
const b=await chromium.launch(); const page=await b.newPage({viewport:{width:390,height:844}});
const seen=[];
page.on('response',async r=>{ const u=r.url(); if(!u.includes('localhost:4194'))return;
  try{ const len=(await r.body()).length; seen.push([u.replace('http://localhost:4194',''),len]); }catch{} });
await page.goto('http://localhost:4194/?preview=1',{waitUntil:'domcontentloaded'});
await page.waitForSelector('.dish-card-cv',{timeout:20000});
await page.waitForTimeout(3000);
const js=seen.filter(([u])=>u.endsWith('.js'));
const img=seen.filter(([u])=>/\.(webp|jpg|png|svg|ico)$/.test(u));
const css=seen.filter(([u])=>u.endsWith('.css'));
const sum=a=>a.reduce((s,[,n])=>s+n,0);
console.log('=== JS loaded on home-page first view ===');
js.sort((a,b)=>b[1]-a[1]).forEach(([u,n])=>console.log('  ',String(Math.round(n/1024)).padStart(5),'KB ',u));
console.log('  ------');
console.log('   JS total  ', Math.round(sum(js)/1024),'KB');
console.log('   CSS total ', Math.round(sum(css)/1024),'KB  (',css.length,'files )');
console.log('   IMG total ', Math.round(sum(img)/1024),'KB  (',img.length,'files )');
console.log('   ALL       ', Math.round(sum(seen)/1024),'KB  (',seen.length,'requests )');
console.log('\n=== all chunks on disk (not all are loaded) ===');
const all=fs.readdirSync(path.join(ROOT,'assets')).filter(f=>f.endsWith('.js'))
  .map(f=>[f,fs.statSync(path.join(ROOT,'assets',f)).size]).sort((a,b)=>b[1]-a[1]);
const loaded=new Set(js.map(([u])=>path.basename(u)));
all.slice(0,14).forEach(([f,n])=>console.log('  ',String(Math.round(n/1024)).padStart(5),'KB ',loaded.has(f)?'[LOADED]':'[lazy]  ',f));
await b.close(); srv.close();
